/* MFL public data layer — edit this file as Season 7 results and profiles are confirmed. */
window.MFL_DATA = {
  season: 'Season 7',
  teams: [
    {name:'Brotherhood-7', group:'A', captain:'Nayem Hossain', href:'team-6.html'},
    {name:'Flame 7X', group:'A', captain:'Rakib Hasan', href:'team-4.html'},
    {name:'Seven Goats', group:'A', captain:'Mehedi Hasan Siam', href:'team-5.html'},
    {name:'Thunder 7', group:'A', captain:'Miraz Hasan', href:'team-3.html'},
    {name:'Avengers', group:'B', captain:'Rassell Islam', href:'team-2.html'},
    {name:'Peace FC', group:'B', captain:'Arman Ahmed', href:'team-8.html'},
    {name:'Iron Titans', group:'B', captain:'Robiul Islam', href:'team-1.html'},
    {name:'7 Knights', group:'B', captain:'Atik Al Shahriar', href:'team-7.html'}
  ],
  season6Standings: {
    A:[
      {team:'Seven Goats',p:3,w:3,d:0,l:0,gf:12,ga:2},
      {team:'Thunder 7',p:3,w:2,d:0,l:1,gf:10,ga:1},
      {team:'Flame 7X',p:3,w:0,d:1,l:2,gf:2,ga:10},
      {team:'Brotherhood-7',p:3,w:0,d:1,l:2,gf:1,ga:11}
    ],
    B:[
      {team:'Iron Titans',p:3,w:2,d:1,l:0,gf:7,ga:2},
      {team:'Avengers',p:3,w:2,d:0,l:1,gf:6,ga:4},
      {team:'7 Knights',p:3,w:1,d:1,l:1,gf:4,ga:4},
      {team:'Peace FC',p:3,w:0,d:0,l:3,gf:2,ga:7}
    ]
  },
  season6Scorers:[
    ['Robiul',7],['Hamim',6],['Miraz',6],['Rassel',5],['Siam',5],['Sohan',5],['Rokon',3],['Tamim',3],['Sadab',2],['Punok',1],['Adib',1],['Nayem',1],['Orik',1],['Arko',1],['Malek',1],['Sultan',1],['Arpo',1],['Leon',1]
  ],
  players:[
    {"name":"Robiul","goals":7,"team":"team-1.html","fullName":"Robiul Islam","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-001","roles":["Captain"]},
    {"name":"Rownok","goals":0,"team":"team-1.html","fullName":"Nasemul Iqbal Rownok","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-002","roles":["Vice-Captain"]},
    {"name":"Sultan","goals":1,"team":"team-1.html","fullName":"Sultan Mahmud","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-003","roles":["Goalkeeper"]},
    {"name":"Dhep","goals":0,"team":"team-1.html","fullName":"AR Dhep","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-004","roles":[]},
    {"name":"Alif","goals":0,"team":"team-1.html","fullName":"AR Alif","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-005","roles":[]},
    {"name":"Apurbo","goals":0,"team":"team-1.html","fullName":"Shah-Neoyaz Apurbo","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-006","roles":[]},
    {"name":"Dulal","goals":0,"team":"team-1.html","fullName":"Dulal Hossain","teamName":"Iron Titans","group":"B","playerId":"MFL-S6-007","roles":[]},
    {"name":"Rassell","goals":0,"team":"team-2.html","fullName":"Rassell Islam","teamName":"Avengers","group":"B","playerId":"MFL-S6-008","roles":["Captain"]},
    {"name":"Hamim","goals":6,"team":"team-2.html","fullName":"Abrar Hamim","teamName":"Avengers","group":"B","playerId":"MFL-S6-009","roles":["Vice-Captain"]},
    {"name":"Atik","goals":0,"team":"team-2.html","fullName":"Atik","teamName":"Avengers","group":"B","playerId":"MFL-S6-010","roles":["Goalkeeper"]},
    {"name":"AR Rafi","goals":0,"team":"team-2.html","fullName":"AR Rafi","teamName":"Avengers","group":"B","playerId":"MFL-S6-011","roles":[]},
    {"name":"Tasin","goals":0,"team":"team-2.html","fullName":"Tasin Islam","teamName":"Avengers","group":"B","playerId":"MFL-S6-012","roles":[]},
    {"name":"Sinha","goals":0,"team":"team-2.html","fullName":"Sinha Prodhan","teamName":"Avengers","group":"B","playerId":"MFL-S6-013","roles":[]},
    {"name":"Tanver Rafi","goals":0,"team":"team-2.html","fullName":"Tanver Rafi","teamName":"Avengers","group":"B","playerId":"MFL-S6-014","roles":[]},
    {"name":"Miraz","goals":6,"team":"team-3.html","fullName":"Miraz Islam","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-015","roles":["Captain"]},
    {"name":"Sadab","goals":2,"team":"team-3.html","fullName":"Khalid Saifullah Sadab","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-016","roles":["Vice-Captain"]},
    {"name":"Yeasin","goals":0,"team":"team-3.html","fullName":"Yeasin Arafat","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-017","roles":["Goalkeeper"]},
    {"name":"Sohan","goals":5,"team":"team-3.html","fullName":"Sohan Islam","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-018","roles":[]},
    {"name":"Leon","goals":1,"team":"team-3.html","fullName":"Leon Hasan","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-019","roles":[]},
    {"name":"Adib","goals":1,"team":"team-3.html","fullName":"Tahmid Rahman Adib","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-020","roles":[]},
    {"name":"Antor","goals":0,"team":"team-3.html","fullName":"Antor Roy","teamName":"Thunder 7","group":"A","playerId":"MFL-S6-021","roles":[]},
    {"name":"Rakib","goals":0,"team":"team-4.html","fullName":"Rakib Islam","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-022","roles":["Captain"]},
    {"name":"Malek","goals":1,"team":"team-4.html","fullName":"Abdul Malek","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-023","roles":["Vice-Captain"]},
    {"name":"Zisun","goals":0,"team":"team-4.html","fullName":"Sh Zisun","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-024","roles":["Goalkeeper"]},
    {"name":"Rohan","goals":0,"team":"team-4.html","fullName":"Rohan Ahmed","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-025","roles":[]},
    {"name":"Soyad","goals":0,"team":"team-4.html","fullName":"Sheikh Munzir Ahmmed Soyad","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-026","roles":[]},
    {"name":"Kabbo","goals":0,"team":"team-4.html","fullName":"Abrar Fiyaz Kabbo","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-027","roles":[]},
    {"name":"Abu Rayhan","goals":0,"team":"team-4.html","fullName":"Abu Rayhan","teamName":"Flame 7X","group":"A","playerId":"MFL-S6-028","roles":[]},
    {"name":"Siam","goals":5,"team":"team-5.html","fullName":"Mehedi Hasan Siam","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-029","roles":["Captain"]},
    {"name":"Abid","goals":0,"team":"team-5.html","fullName":"Abid IStiyaq","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-030","roles":["Vice-Captain"]},
    {"name":"Pulok","goals":0,"team":"team-5.html","fullName":"Pulok Roy","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-031","roles":["Goalkeeper"]},
    {"name":"Elhan","goals":0,"team":"team-5.html","fullName":"Fahim Al Shariar Elhan","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-032","roles":[]},
    {"name":"Polash","goals":0,"team":"team-5.html","fullName":"Polash Ahmed","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-033","roles":[]},
    {"name":"Rokon","goals":3,"team":"team-5.html","fullName":"AR Rokon","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-034","roles":[]},
    {"name":"Tonmoy","goals":0,"team":"team-5.html","fullName":"AS Tonmoy Chowdhury","teamName":"Seven Goats","group":"A","playerId":"MFL-S6-035","roles":[]},
    {"name":"Nayem","goals":1,"team":"team-6.html","fullName":"Nayem Hossain","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-036","roles":["Captain"]},
    {"name":"Orik","goals":1,"team":"team-6.html","fullName":"Orik Azmain","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-037","roles":["Vice-Captain"]},
    {"name":"Junayed","goals":0,"team":"team-6.html","fullName":"Iqbal Kaysar Junayed","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-038","roles":["Goalkeeper"]},
    {"name":"Abu","goals":0,"team":"team-6.html","fullName":"Iqbal Abu","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-039","roles":[]},
    {"name":"Labib","goals":0,"team":"team-6.html","fullName":"Labib Islam","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-040","roles":[]},
    {"name":"Minhaz","goals":0,"team":"team-6.html","fullName":"Minhaz Rahman","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-041","roles":[]},
    {"name":"Arko","goals":1,"team":"team-6.html","fullName":"Abid Arko","teamName":"Brotherhood-7","group":"A","playerId":"MFL-S6-042","roles":[]},
    {"name":"Atik","goals":0,"team":"team-7.html","fullName":"Atique Al Shahriar","teamName":"7 Knights","group":"B","playerId":"MFL-S6-043","roles":["Captain"]},
    {"name":"Bishal","goals":0,"team":"team-7.html","fullName":"Mahabub Alam Bishal","teamName":"7 Knights","group":"B","playerId":"MFL-S6-044","roles":["Vice-Captain"]},
    {"name":"Rasel","goals":0,"team":"team-7.html","fullName":"Rasel Islam","teamName":"7 Knights","group":"B","playerId":"MFL-S6-045","roles":["Goalkeeper"]},
    {"name":"Sakib","goals":0,"team":"team-7.html","fullName":"Sakib","teamName":"7 Knights","group":"B","playerId":"MFL-S6-046","roles":[]},
    {"name":"Tamim","goals":3,"team":"team-7.html","fullName":"Abu Rahat Tamim","teamName":"7 Knights","group":"B","playerId":"MFL-S6-047","roles":[]},
    {"name":"Rupok","goals":0,"team":"team-7.html","fullName":"Imran Khan Rupok","teamName":"7 Knights","group":"B","playerId":"MFL-S6-048","roles":[]},
    {"name":"Anik","goals":0,"team":"team-7.html","fullName":"Anik Roy","teamName":"7 Knights","group":"B","playerId":"MFL-S6-049","roles":[]},
    {"name":"Arman","goals":0,"team":"team-8.html","fullName":"Arman Ahmed","teamName":"Peace FC","group":"B","playerId":"MFL-S6-050","roles":["Captain","Goalkeeper"]},
    {"name":"SM Sadid","goals":0,"team":"team-8.html","fullName":"SM Sadid","teamName":"Peace FC","group":"B","playerId":"MFL-S6-051","roles":["Vice-Captain"]},
    {"name":"Bappy","goals":0,"team":"team-8.html","fullName":"Bappy","teamName":"Peace FC","group":"B","playerId":"MFL-S6-052","roles":[]},
    {"name":"Awpurbo","goals":0,"team":"team-8.html","fullName":"Toufiq Elahi Awpurbo","teamName":"Peace FC","group":"B","playerId":"MFL-S6-053","roles":[]},
    {"name":"Shakib","goals":0,"team":"team-8.html","fullName":"Shakib Al Hasan","teamName":"Peace FC","group":"B","playerId":"MFL-S6-054","roles":[]},
    {"name":"SD. Sadid","goals":0,"team":"team-8.html","fullName":"SD. Sadid","teamName":"Peace FC","group":"B","playerId":"MFL-S6-055","roles":[]},
    {"name":"Arpo","goals":1,"team":"team-8.html","fullName":"Abid Arpo","teamName":"Peace FC","group":"B","playerId":"MFL-S6-056","roles":[]}
  ],
  records:[
    {label:'Season 6 Champion',value:'Iron Titans',detail:'MFL Season 6'},
    {label:'Season 6 Runner-up',value:'Avengers',detail:'MFL Season 6'},
    {label:'Season 6 Golden Boot',value:'Robiul',detail:'7 goals'},
    {label:'Highest scorer count',value:'7 goals',detail:'Robiul — Season 6'}
  ]
};
